estoque/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add_produto/<slug:slug>', views.add_produto, name="add_produto"),#Adicionar Produto
    path('add_produto_redirect/<slug:slug>', views.add_produto_redirect, name="add_produto_redirect"),#Adicionar Produto Redirect

    path('excluir_produto/<slug:slug>/', views.excluir_produto, name="excluir_produto"),#Excluir Produto
    path('produto/<slug:slug>', views.produto, name="produto"),#Editar Produto

    path('pre_vendas/<slug:slug>', views.pre_vendas, name="pre_vendas"),#Antes da Venda
    path('consultar_vendas_geral/<slug:slug>', views.consultar_vendas_geral, name="consultar_vendas_geral"),#Consultar Vendas Geral Não Finalizadas
    path('consultar_vendas/<slug:slug>', views.consultar_vendas, name="consultar_vendas"),#Consultar Vendas Não Finalizadas
    path('consultar_vendas_finalizadas/<slug:slug>', views.consultar_vendas_finalizadas, name="consultar_vendas_finalizadas"),#Consultar Vendas Finalizadas
    path('vendas/<slug:slug>', views.vendas, name="vendas"),#Vender Produto
    path('visualizar_vendas/<slug:slug>', views.visualizar_vendas, name="visualizar_vendas"),#Visualizar Vendas

    path('conferir_vendas_geral/<slug:slug>', views.conferir_vendas_geral, name="conferir_vendas_geral"),#Conferir Vendas Geral (antes de finalizar a venda)
    path('vendas_finalizadas/<slug:slug>', views.vendas_finalizadas, name="vendas_finalizadas"),#Finalizar Venda dos Produtos
    path('visualizar_vendas_finalizadas/<slug:slug>', views.visualizar_vendas_finalizadas, name="visualizar_vendas_finalizadas"),#Visualizar Vendas Finalizadas

    path('excluir_venda/<slug:slug>/', views.excluir_venda, name="excluir_venda"),#Excluir Venda
    # path('confirmar_venda/<slug:slug>/', views.confirmar_venda, name="confirmar_venda"),#Confirmar Venda -- Comentado pois não será mais necessário
    path('excluir_venda_geral/<slug:slug>/', views.excluir_venda_geral, name="excluir_venda_geral"),#Excluir Venda Geral
    path('confirmar_venda_geral/<slug:slug>/', views.confirmar_venda_geral, name="confirmar_venda_geral"),#Confirmar Venda Geral

    path('add_novonome_produto/<slug:slug>/', views.add_novonome_produto, name="add_novonome_produto"),#Adicionar Novo Nome de Produto
    path('excluir_novonome_produto/<slug:slug>/', views.excluir_novonome_produto, name="excluir_novonome_produto"),#Excluir Novo Nome do Produto


    path('cadastrar_comunidade/', views.cadastrar_comunidade, name="cadastrar_comunidade"),#Cadastrar Comunidade

    path('listar_logs/', views.listar_logs, name="listar_logs"),#Acessar Logs

    path('export_entrada_produtos/<slug:slug>', views.export_entrada_produtos, name="export_entrada_produtos"),#Acessar Logs Export Entrada Produtos

    path('export_csv_vendas/<slug:slug>', views.export_csv_vendas, name='export_csv_vendas'),#Exportar CSV Vendas
    path('export_csv_vendas_finalizadas/<slug:slug>', views.export_csv_vendas_finalizadas, name='export_csv_vendas_finalizadas'),#Exportar CSV Vendas Finalizadas
    path('export_csv_produto/<slug:slug>', views.export_csv_produto, name='export_csv_produto'),#Exportar CSV Produtos
]

merceariacomunitaria/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import os

if os.environ.get('DJANGO_ENV') == 'production':
    urlpatterns = [
        re_path(r'^app/media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
        re_path(r'^app/static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
        path('admin/', admin.site.urls),
        path('', include('estoque.urls')),
        path('', include('usuarios.urls')),
    ]
else:
    urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('estoque.urls')),
        path('', include('usuarios.urls')),
    ]

if os.environ.get('DJANGO_ENV') == 'development':
    urlpatterns += staticfiles_urlpatterns()
else:
    pass
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = 'estoque.views.error_500'
handler404 = 'estoque.views.error_404'
handler403 = 'estoque.views.error_403'

estoque/models.py
from django.db import models
from django.template.defaultfilters import slugify
from datetime import date, datetime
from django.utils import timezone

class Comunidade(models.Model):
    id = models.AutoField(primary_key=True)
    nome_comunidade = models.CharField(max_length=60, unique=False)
    cidade = models.CharField(max_length=60, unique=False, null=True, blank=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    cnpj = models.CharField(max_length=18, null=True, blank=True, unique=True)
    tipo = models.CharField(max_length=20, unique=False, null=True, editable=False)
    responsavel_01 = models.CharField(max_length=128, unique=False, null=True, editable=False)
    celular_01 = models.CharField(max_length=15, unique=False, null=True, editable=False)
    responsavel_02 = models.CharField(max_length=128, unique=False, null=True, editable=False)
    celular_02 = models.CharField(max_length=15, unique=False, null=True, editable=False)
    ativo = models.CharField(max_length=3, unique=False, null=True, editable=False)
    criado_por = models.CharField(max_length=128, unique=False, null=True, editable=False)
    data_criacao = models.CharField(max_length=20, null=True, editable=False)
    alterado_por = models.CharField(max_length=128, unique=False, null=True, editable=False)
    data_alteracao = models.CharField(max_length=20, null=True, editable=False)

    def __str__(self):
        return self.nome_comunidade

    def save(self, *args, **kwargs):#Criando Slug para buscas e Data_Criação
        if not self.slug:
            self.slug = slugify(f"{self.nome_comunidade} {self.cidade}")
            data_modelo = timezone.localtime(timezone.now())
            data_modelo_1 = data_modelo.strftime("%d/%m/%Y %H:%M:%S") 
            self.data_criacao = data_modelo_1
        return super().save(*args, **kwargs) 


class NomeProduto(models.Model):
    nome_produto = models.CharField(max_length=128)
    slug = models.SlugField(unique=True, blank=True, null=True)
    criado_por = models.CharField(max_length=128, unique=False, null=True, editable=False)
    data_criacao = models.CharField(max_length=20, null=True, editable=False)
    nome_comunidade = models.ForeignKey(Comunidade, on_delete=models.PROTECT, null=True)
    nome_comunidade_str = models.CharField(max_length=60, unique=False, null=True, blank=True)
    cidade_comunidade = models.CharField(max_length=60, unique=False, null=True, blank=True)

    def __str__(self):
        return self.nome_produto

    def save(self, *args, **kwargs):#Criando Slug para buscas e Data_Criação
        if not self.slug:
            data_modelo = timezone.localtime(timezone.now())
            data_modelo_1 = data_modelo.strftime("%d/%m/%Y %H:%M:%S") 
            self.data_criacao = data_modelo_1
            self.slug = slugify(self.nome_produto + "-" + self.nome_comunidade_str + "-" + self.cidade_comunidade)
        return super().save(*args, **kwargs)


class Produto(models.Model):
    nome_produto = models.ForeignKey(NomeProduto, on_delete=models.PROTECT, null=True)
    label = models.CharField(max_length=128, blank=True, null=True)
    quantidade = models.PositiveIntegerField()
    preco_compra = models.DecimalField(max_digits=7, decimal_places=2)
    preco_venda = models.DecimalField(max_digits=7, decimal_places=2)
    slug = models.SlugField(unique=True, blank=True, null=True)
    criado_por = models.CharField(max_length=128, unique=False, null=True, editable=False)
    data_criacao = models.CharField(max_length=20, null=True, editable=False)
    alterado_por = models.CharField(max_length=128, unique=False, null=True, editable=False)
    data_alteracao = models.CharField(max_length=20, null=True, editable=False)
    nome_comunidade = models.ForeignKey(Comunidade, on_delete=models.PROTECT, null=True)
    alterando_produto = models.CharField(max_length=128, unique=False, default=0)
    ultimo_acesso = models.CharField(max_length=20, default=0)
    cod_produto = models.CharField(max_length=10, blank=True, null=True)
    cod_barras = models.CharField(max_length=50, blank=True, null=True)
    peso = models.DecimalField(max_digits=5, decimal_places=3, default=0)
    tipo_peso = models.CharField(max_length=2, default=0)

    def equals(self, other):
        """Compara se dois objetos Produto são iguais"""
        if not isinstance(other, Produto):
            return False
        return (
            self.quantidade == other.quantidade and
            self.preco_compra == other.preco_compra and
            self.preco_venda == other.preco_venda
        )

    def __str__(self):
        return self.nome_produto

    def save(self, *args, **kwargs):
        if not self.data_criacao:
            data_modelo2 = timezone.localtime(timezone.now())
            data_criacao_m = data_modelo2.strftime("%d/%m/%Y %H:%M:%S")
            self.data_criacao = data_criacao_m
        # salva o produto
        super().save(*args, **kwargs)


class P_Excel(models.Model):
    data = models.CharField(max_length=20, null=True, editable=False)
    acao = models.CharField(max_length=20)
    id_user = models.IntegerField(blank=True, null=True)
    nome_user = models.CharField(max_length=128, unique=False, blank=True, null=True, editable=False)
    nome_produto = models.CharField(max_length=128, unique=False)
    quantidade = models.PositiveIntegerField()
    estorno = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    preco_compra = models.DecimalField(max_digits=7, decimal_places=2)
    preco_venda = models.DecimalField(max_digits=7, decimal_places=2)
    peso = models.DecimalField(max_digits=5, decimal_places=3, default=0)
    dia = models.CharField(max_length=10, null=True, editable=False)
    nome_e_cidade_comunidade = models.CharField(max_length=128, default=0)
    ultima_alteracao = models.CharField(max_length=20, null=True, editable=False)
    alterado_por = models.CharField(max_length=128, unique=False, blank=True, null=True, editable=False)

    def save(self, *args, **kwargs):
        if not self.acao:
            self.acao = 'Inclusão' if not self.id else 'Alteração'
            data_modelo2 = timezone.localtime(timezone.now())
            data_criacao_m = data_modelo2.strftime("%d/%m/%Y %H:%M:%S")
            data_criacao_g = data_modelo2.strftime("%d/%m/%Y")
            self.data = data_criacao_m
            data_criacao_g = datetime.strptime(data_criacao_g, "%d/%m/%Y").date()
            self.dia = data_criacao_g

        if not self.data:
            data_modelo2 = timezone.localtime(timezone.now())
            data_criacao_m = data_modelo2.strftime("%d/%m/%Y %H:%M:%S")
            data_criacao_g = data_modelo2.strftime("%d/%m/%Y")
            self.data = data_criacao_m
            data_criacao_g = datetime.strptime(data_criacao_g, '%d/%m/%Y').date()
            self.dia = data_criacao_g
        super().save(*args, **kwargs)


class LogsItens(models.Model):
    id_user = models.IntegerField(blank=True, null=True)
    nome_user = models.CharField(max_length=128, unique=False, blank=True, null=True, editable=False)
    nome_objeto = models.CharField(max_length=128, blank=True)
    data = models.CharField(max_length=20, null=True, editable=False)
    dia = models.CharField(max_length=10, null=True, editable=False)
    model = models.CharField(max_length=50)
    acao = models.CharField(max_length=20)
    campos_inclusao = models.TextField(blank=True)
    valores_inclusao = models.TextField(default="")
    campos_alteracao = models.TextField()
    valores_antigos = models.TextField(default="")
    valores_novos = models.TextField(default="")
    campos_exclusao = models.TextField(blank=True)
    valores_exclusao = models.TextField(default="")

    def save(self, *args, **kwargs):
        if not self.acao:
            self.acao = 'Inclusão' if not self.id else 'Alteração'
            data_modelo2 = timezone.localtime(timezone.now())
            data_criacao_m = data_modelo2.strftime("%d/%m/%Y %H:%M:%S")
            data_criacao_g = data_modelo2.strftime("%d/%m/%Y")
            self.data = data_criacao_m
            data_criacao_g = datetime.strptime(data_criacao_g, "%d/%m/%Y").date()
            self.dia = data_criacao_g

        if not self.data:
            data_modelo2 = timezone.localtime(timezone.now())
            data_criacao_m = data_modelo2.strftime("%d/%m/%Y %H:%M:%S")
            data_criacao_g = data_modelo2.strftime("%d/%m/%Y")
            self.data = data_criacao_m
            data_criacao_g = datetime.strptime(data_criacao_g, '%d/%m/%Y').date()
            self.dia = data_criacao_g
        super().save(*args, **kwargs)


class VendasControle(models.Model):
    nome_cliente = models.CharField(max_length=128, unique=False, null=True, editable=False)
    id_venda = models.CharField(max_length=10, primary_key=True)
    preco_venda_total = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True, editable=False)
    peso_venda_total = models.DecimalField(max_digits=5, decimal_places=3, default=0)
    slug = models.SlugField(unique=True, blank=True, null=True)
    venda_finalizada = models.IntegerField(null=False, blank=False)
    nome_comunidade = models.ForeignKey(Comunidade, on_delete=models.PROTECT, null=True)
    alteracoes_finalizadas = models.BooleanField(null=False, blank=False)
    novo_preco_venda_total = models.DecimalField(max_digits=7, decimal_places=2)
    valor_cancelado = models.DecimalField(max_digits=7, decimal_places=2)
    valor_pago = models.DecimalField(max_digits=7, decimal_places=2)
    valor_realmente_pago = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    troco = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    falta_editar = models.IntegerField(null=False, blank=False)
    falta_c_ou_e = models.IntegerField(null=False, blank=False)
    forma_venda = models.CharField(max_length=8, null=True, blank=True)

estoque/forms.py
from django import forms
from .models import Produto, Comunidade

#Criando Formulário de alteração dos Produtos
class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        exclude = ['label', 'nome_produto', 'slug', 'preco_venda', 'nome_comunidade', 'alterando_produto', 'ultimo_acesso', 'cod_barras', 'cod_produto', 'peso']
        widgets = {
            'preco_compra': forms.TextInput(attrs={'type': 'text'}),
            'quantidade': forms.TextInput(attrs={'disabled': True}),
        }

class ComunidadeForm(forms.ModelForm):
    class Meta:
        model = Comunidade
        exclude = ['nome_comunidade', 'slug']

estoque/templates/add_produto.html
{% extends 'base.html' %}
{% load define_action %}

{% block 'body' %}
<div class="container">
            <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}

            <br>
            <label>Selecione o nome do produto:</label>
            <select class="form-control" onchange="funcao(this.value)" name="nome_produto" id="nome_produto">
                {% for nome_produto in nome_produtos %}
                <option value="{{nome_produto.nome_produto}}">{{nome_produto.nome_produto}}</option>
                {% endfor %}
            </select>

            <br>

            <label>Quantidade:</label>
            <input class="form-control" type="text" name="quantidade" id="quantidade" placeholder="0">

            <br>

            <label>Peso:</label>
            <input class="form-control" type="text" name="peso" id="peso" placeholder="Exemplo: 0.500 = (500g/ml), 1.000 = (1kg/ml)">

            <br>
            
            <label>Selecione o tipo do produto:</label>
            <select class="form-control" name="tipo_peso" id="tipo_peso">
                <option value="KG">KG</option>
                <option value="ML">ML</option>
            </select>

            <br>

            <label>Preço de Compra:</label>
            <input class="form-control" type="text" name="preco_compra" id="preco_compra" placeholder="0">

            <br>

            <input type="submit" id='Enviar' value="Criar" class="btn btn-primary">
            </form>
            
            <hr style="background-color: gray;">

        <form action="" method="GET">
            <div class="row d-flex">
                <div class="col-md">
                    <input class="form-control" type="text" name="nome_produto" placeholder="Nome...">
                </div>

                <div class="col-md">
                    <input class="form-control" type="text" name="preco_min" id="preco_min" placeholder="Preço Mínimo">
                </div>
                
                <div class="col-md">
                    <input class="form-control" type="text" name="preco_max" id="preco_max" placeholder="Preço Máximo">
                </div>
                <div>
                    &nbsp; &nbsp;<input type="submit" value="Filtrar" id="filtrar_add_produto" class="btn btn-success">
                </div>

                {% if user.cargo == "A" or user.cargo == "R" or user.cargo == "O"  %}
                <div class="col-md">
                    <a class="btn btn-info" id="exportar_add_produto" href="{% url 'export_entrada_produtos' slug%}">Exportar Planilha</a>
                </div>
                {% endif %}
            </div>
        </form>
            <br>
        <div class="listar_produtos">
            <div class="row">
            <div>

            </div>
            {% for produto in produtos %}
                <div class="col-md">
                    <div style="background-color: #e0ffff; width: 18rem" class="card" style="width: 18rem;">
                        <div class="card-body">
                            {% if "Sem Cor" in produto.label %}
                                <h5 class="card-title">{{produto.nome_produto}}</h5>
                            {% else %}
                                <h5 class="card-title">{{produto.label}}</h5>
                            {% endif %}
                            <h6 class="card-title">Quantidade em Estoque: {{produto.quantidade}}</h6>
                            {% define produto.slug as slugproduto %}
                            <a href="{% url 'produto' produto.slug %}" class="btn btn-primary">Alterar</a>
                            <a onclick="excluirProduto(`{{slugproduto}}`)" class="btn btn-danger">Excluir</a>
                        </div>
                    </div>
                    <br>
                </div>
            {% endfor %}
            </div>
        </div>

</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function(){
        $('#quantidade').mask('000')
        $('#preco_compra').mask('000,00', {reverse: true})
        $('#preco_min').mask('000,00', {reverse: true})
        $('#preco_max').mask('000,00', {reverse: true})
        $('#peso').mask('0.000')
    });

    //Ordenar o nome dos produtos ao carregar a tela
    window.onload = function() {
        //Inicio Nome Produto
        var itensOrdenados = $('#nome_produto option').sort(function (a, b) {
            return a.text < b.text ? -1 : 1;
        });
    
        $('#nome_produto').html(itensOrdenados);
        //Fim Nome Produto
    }

</script>
{% endblock %}

estoque/templates/cadastrar_comunidade.html
{% extends 'base.html' %}

{% block 'body' %}
<div class="container">
    <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}   
    <br>
    <label>CNPJ:</label>
    <input class="form-control" type="text" name="cnpj" id="cnpj">
    <br>
    <label>Tipo:</label>
    <select class="form-control" name="tipo" id="tipo">
        <option value="ONG">ONG</option>
        <option value="IGREJA">IGREJA</option>
        <option value="ASSOCIACAO">ASSOCIAÇÃO</option>
        <option value="OUTROS">OUTROS</option>
    </select>
    <br>
    <label>Nome da Comunidade:</label>
    <input class="form-control" type="text" name="nome_comunidade" id="nome_comunidade">
    <br>
    <label>Cidade:</label>
    <input class="form-control" type="text" name="cidade" id="cidade">
    <br>
    <label>Responsável 01:</label>
    <input class="form-control" type="text" name="responsavel_01" id="responsavel_01">
    <br>
    <label>Celular 01:</label>
    <input class="form-control" type="text" name="celular_01" id="celular_01">
    <br>
    <label>Responsável 02:</label>
    <input class="form-control" type="text" name="responsavel_02" id="responsavel_02">
    <br>
    <label>Celular 02:</label>
    <input class="form-control" type="text" name="celular_02" id="celular_02">
    <br>
    <input type="submit" value="Criar" class="btn btn-primary">
    </form>
</div>
{% endblock %}

{% block scripts %}

<style>
    .valid {
        background-color: #d4edda !important; /* Fundo verde claro para indicar campo válido */
    }

    .invalid {
        background-color: #f8d7da !important; /* Fundo vermelho claro para indicar campo inválido */
    }
</style>

<script>
    $(document).ready(function(){
        $('#cnpj').mask('00.000.000/0000-00')
        $('#celular_01').mask('(00) 0000-00009', {
            onKeyPress: function (val, e, field, options) {
                // Aplica a máscara adequada dependendo do comprimento do número digitado
                field.mask(val.length > 14 ? '(00) 00000-0000' : '(00) 0000-00009', options);
            }
        });
        $('#celular_02').mask('(00) 0000-00009', {
            onKeyPress: function (val, e, field, options) {
                // Aplica a máscara adequada dependendo do comprimento do número digitado
                field.mask(val.length > 14 ? '(00) 00000-0000' : '(00) 0000-00009', options);
            }
        });
        
        // Validações do CNPJ
        $('#cnpj').on('input', function () {
            let cnpj = $(this).val();
            if (validateCNPJ(cnpj)) {
                $(this).removeClass('invalid').addClass('valid');
                $('form input[type="submit"]').prop('disabled', false);
            } else {
                $(this).removeClass('valid').addClass('invalid');
                $('form input[type="submit"]').prop('disabled', true);
            }
        });

        $('form').on('submit', function(e) { // Adicionado aqui
            // Bloqueia o envio se o CNPJ não for válido
            if (!validateCNPJ($('#cnpj').val())) {
                e.preventDefault();
                alert('CNPJ inválido. Corrija antes de enviar.');
            }
        });

        // Função de validação de CNPJ
        function validateCNPJ(cnpj) {
            cnpj = cnpj.replace(/[^\d]+/g, ''); // Remove caracteres não numéricos

            if (cnpj.length !== 14) return false;

            // Elimina CNPJs inválidos conhecidos
            if (/^(\d)\1+$/.test(cnpj)) return false;

            // Valida os dois dígitos verificadores
            let tamanho = cnpj.length - 2;
            let numeros = cnpj.substring(0, tamanho);
            let digitos = cnpj.substring(tamanho);
            let soma = 0;
            let pos = tamanho - 7;

            for (let i = tamanho; i >= 1; i--) {
                soma += numeros.charAt(tamanho - i) * pos--;
                if (pos < 2) pos = 9;
            }

            let resultado = soma % 11 < 2 ? 0 : 11 - (soma % 11);
            if (resultado != digitos.charAt(0)) return false;

            tamanho = tamanho + 1;
            numeros = cnpj.substring(0, tamanho);
            soma = 0;
            pos = tamanho - 7;

            for (let i = tamanho; i >= 1; i--) {
                soma += numeros.charAt(tamanho - i) * pos--;
                if (pos < 2) pos = 9;
            }

            resultado = soma % 11 < 2 ? 0 : 11 - (soma % 11);
            if (resultado != digitos.charAt(1)) return false;

            return true;
        }
    });



</script>
{% endblock %}

estoque/templates/consultar_vendas.html
{% extends 'base.html' %}

{% block 'body' %}
<div class="container">
    <br>
    <h2 class="text-center my-4">SELECIONE UM PRODUTO</h2>
    <div class="produtos-container">
        {% for venda in vendas %}
            {% if venda.venda_finalizada == 0 %}
            <div class="produto-card" data-slug="{{ venda.slug }}" data-url="{% url 'visualizar_vendas' venda.slug %}" onclick="window.location.href=this.dataset.url;">
                    <h5 class="card-title">{{venda.label_vendas_get}}</h5>
                    <h5 class="card-title">Cliente: {{venda.nome_cliente}}</h5>
                    <a href="{% url 'visualizar_vendas' venda.slug %}" class="btn btn-primary">Visualizar</a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <br>
    <a href="{% url 'consultar_vendas_geral' slug %}" class="btn btn-primary">Voltar</a>
    <br>
</div>

{% endblock %}

estoque/templates/consultar_vendas_finalizadas.html
{% extends 'base.html' %}

{% block 'body' %}
<div class="container">
    <br>
    <h2 class="text-center my-4">SELECIONE UM PRODUTO</h2>
    <div class="produtos-container">
        {% for venda in vendas %}
            {% if venda.venda_finalizada == 1 %}
            <div class="produto-card" data-slug="{{ venda.slug }}" data-url="{% url 'visualizar_vendas_finalizadas' venda.slug %}" onclick="window.location.href=this.dataset.url;">
                    <h5 class="card-title">{{venda.label_vendas_get}}</h5>
                    <h5 class="card-title">Cliente: {{venda.nome_cliente}}</h5>
                    <a href="{% url 'visualizar_vendas_finalizadas' venda.slug %}" class="btn btn-primary">Visualizar</a>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    <br>
    <a href="{% url 'vendas_finalizadas' slug %}" class="btn btn-primary">Voltar</a>
    <br>
</div>

{% endblock %}

estoque/templates/editar_comunidade.html
{% extends 'base.html' %}
{% load static%}

{% block 'body' %}
    <div class="container">
        {% if user.cargo == "A" or user.cargo == "P" or user.cargo == "CF" %} 
            {% if ano_atual_str == data_modelo_1 %}
            <h1>Festa {{ano_atual_str}}</h1>
                <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                    <table>
                        {{form.as_table}}
                    </table>
                    <button type="submit" class="btn btn-success">Salvar</button>
                </form>
            {% endif %}
        {% endif %}
    </div>
{% endblock %}

estoque/templates/produto.html
{% extends 'base.html' %}
{% load static%}

{% block 'body' %}
    <div class="container">
        <h1>Produto: {{nome_produto}}</h1>

        <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <table>
                {{form.as_table}}
            </table>
            <br>
            <div class="input-row">
                <h6>Abastecer Quantidade:</h6> &nbsp;
                <input class="form-control quantity-input" style="width: 8em;" type="text" name="abastecer_quantidade" id="abastecer_quantidade">
            </div>
            <button type="submit" class="btn btn-success">Salvar</button>
        </form>
    </div>
{% endblock %}

{% block scripts %}
<script>

    $(document).ready(function(){
        $('#id_quantidade').mask('000')
        $('#id_preco_compra').mask('000,00', {reverse: true})
        $('#abastecer_quantidade').mask('000')
        $('#id_peso').mask('0.000')

        $('#id_tipo_peso').mask('AA')
        // Máscara para aceitar apenas letras maiúsculas
        $('#id_tipo_peso').on('input', function() {
            // Transforma o valor em maiúsculas
            let value = $(this).val().toUpperCase();

            // Remove caracteres que não são letras
            value = value.replace(/[^A-Z]/g, '');

            // Atualiza o valor do campo
            $(this).val(value);
        });
    });

</script>
{% endblock %}